### ISSUE TITLE
Unable to run successfully cypress-axe

### ISSUE THREAD

**Issue by pgroot91** [avanslaars/cypress-axe#13]
Having trouble running tests and get the following error:

```
cypress_runner.js:157775 TypeError: Cannot read property 'run' of undefined
    at Context.<anonymous> (https://qa1.domain.com/__cypress/tests?p=cypress\support\index.js-350:18962:22)
From previous event:
    at Context.thenFn (https://qa1.domain.com/__cypress/runner/cypress_runner.js:71909:23)
    at Context.then (https://qa1.domain.com/__cypress/runner/cypress_runner.js:72229:21)
    at Context.<anonymous> (https://qa1.domain.com/__cypress/runner/cypress_runner.js:80256:21)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:79783:33
From previous event:
    at runCommand (https://qa1.domain.com/__cypress/runner/cypress_runner.js:79765:14)
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:79900:14)
From previous event:
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:79900:34)
From previous event:
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:79937:37
From previous event:
    at run (https://qa1.domain.com/__cypress/runner/cypress_runner.js:79929:15)
    at Object.cy.<computed> [as percySnapshot] (https://qa1.domain.com/__cypress/runner/cypress_runner.js:80290:11)
    at Context.runnable.fn (https://qa1.domain.com/__cypress/runner/cypress_runner.js:80477:20)
    at callFn (https://qa1.domain.com/__cypress/runner/cypress_runner.js:30713:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa1.domain.com/__cypress/runner/cypress_runner.js:30706:7)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:84151:28
From previous event:
    at Object.onRunnableRun (https://qa1.domain.com/__cypress/runner/cypress_runner.js:84140:17)
    at $Cypress.action (https://qa1.domain.com/__cypress/runner/cypress_runner.js:78413:30)
    at Test.Runnable.run (https://qa1.domain.com/__cypress/runner/cypress_runner.js:82943:20)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://qa1.domain.com/__cypress/runner/cypress_runner.js:31180:10)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:31286:12
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:31100:14)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:31110:7
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:31042:14)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:31073:7
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:84079:16)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:84097:11
From previous event:
    at onNext (https://qa1.domain.com/__cypress/runner/cypress_runner.js:84094:57)
    at done (https://qa1.domain.com/__cypress/runner/cypress_runner.js:30674:5)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:30718:11
From previous event:
    at callFn (https://qa1.domain.com/__cypress/runner/cypress_runner.js:30717:10)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://qa1.domain.com/__cypress/runner/cypress_runner.js:30706:7)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:84151:28
From previous event:
    at Object.onRunnableRun (https://qa1.domain.com/__cypress/runner/cypress_runner.js:84140:17)
    at $Cypress.action (https://qa1.domain.com/__cypress/runner/cypress_runner.js:78413:30)
    at Hook.Runnable.run (https://qa1.domain.com/__cypress/runner/cypress_runner.js:82943:20)
    at next (https://qa1.domain.com/__cypress/runner/cypress_runner.js:31056:10)
    at https://qa1.domain.com/__cypress/runner/cypress_runner.js:31078:5
    at timeslice (https://qa1.domain.com/__cypress/runner/cypress_runner.js:26146:27)
```

My package:

```
{
	"devDependencies": {
		"@cypress/code-coverage": "^1.8.0",
		"@percy/cypress": "^2.0.0",
		"axe-core": "^3.3.1",
		"concurrently": "^4.1.1",
		"cypress": "^3.4.1",
		"cypress-axe": "^0.5.1",
		"fs-extra": "^8.1.0",
		"istanbul-lib-coverage": "^2.0.5",
		"mocha": "^5.2.0",
		"mocha-multi-reporters": "^1.1.7",
		"mochawesome": "^4.1.0",
		"mochawesome-merge": "^2.0.1",
		"mochawesome-report-generator": "^4.0.1",
		"nyc": "^14.1.1"
	},
	"dependencies": {
		"ls": "^0.2.1",
		"rimraf": "^2.6.3",
		"yargs": "^13.3.0"
	}
}
```

My test:

```
describe('APPB', function () {
	context('[Login] Login into account', function () {
		beforeEach(function(){
		  cy.visit('/login')
		  cy.injectAxe()
		})
		it('[Login] Redirects to /dashboard on success', function () {
			cy.percySnapshot('testing before')
			
			cy.get('input[name=username]').should('have.attr', 'placeholder', 'Username or Email address')
				.type('patrick@domain.com', { delay: 50 }).should('have.value', 'patrick@domain.com')
			cy.get('input[name=password]').should('have.attr', 'placeholder', 'Password')
				.type('12345678', { delay: 50 }).should('have.value', '12345678')
			
			cy.percySnapshot('testing after')
			
			cy.get('button.button.primary').contains('Sign in').click() 
			cy.checkA11y()
		})
	})
})
```
Any ideas or suggestions on what could be wrong with my setup and or test?

**Comment by Webbanditten** [comment]
beforeEach is a global method you should put it in the context of "describe".

So instead of putting it in context but it outside context inside describe.

**Comment by pgroot91** [comment]
@Webbanditten thanks for the explanation and this really blows my mind and it is indeed working as you said putting outside of the context 👍 

describe('APPB', function () {
        beforeEach(function(){
		  cy.injectAxe()
        })
	context('[Login] Login into account', function () {
		before(function(){
		  cy.visit('/login')
		})
		it('[Login] Redirects to /dashboard on success', function () {
			cy.percySnapshot('testing before')
			
			cy.get('input[name=username]').should('have.attr', 'placeholder', 'Username or Email address')
				.type('patrick@domain.com', { delay: 50 }).should('have.value', 'patrick@domain.com')
			cy.get('input[name=password]').should('have.attr', 'placeholder', 'Password')
				.type('12345678', { delay: 50 }).should('have.value', '12345678')
			
			cy.percySnapshot('testing after')
			
                        cy.checkA11y()

			cy.get('button.button.primary').contains('Sign in').click() 
		})
	})
})

I ended up using the following example from cypress: https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__a11y
